# Generated by Django 6.0.1 on 2026-01-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
    ]
